In [6]:
#numpy ---> it is a library used for working with arrays
#it also has functions such as linear algrebra,fourier transformer,matrices...
import numpy
print(numpy.__dir__()) #printing all libraries of numpy

['median', 'real', 'sum', 'integer', '_UFUNC_API', 'sys', 'NAN', 'mat', 'intp', 'logspace', 'triu_indices_from', 'nditer', 'arctan', 'ravel_multi_index', 'longcomplex', 'clip', 'seterrcall', 'fabs', 'generic', 'sort', 'flip', 'cosh', 'isreal', 'concatenate', 'log2', 'bitwise_and', 'ushort', 'cross', 'SHIFT_UNDERFLOW', 'resize', 'RankWarning', 'set_printoptions', 'nanargmin', 'power', 'conjugate', 'ulonglong', 'all', 'nbytes', 'errstate', 'tanh', 'multiply', 'broadcast_shapes', '__path__', 'fromiter', 'dtype', 'mean', 'object_', 'partition', 'fastCopyAndTranspose', 'einsum', '__deprecated_attrs__', 'sometrue', 'matrixlib', 'pi', 'nanmedian', 'polynomial', 'reciprocal', '__file__', 'apply_over_axes', 'in1d', 'where', '__version__', 'r_', 'nancumsum', 'ufunc', 'deprecate_with_doc', 'issctype', 'printoptions', 'log10', 'lookfor', 'test', 'require', 'asfortranarray', 'is_busday', 'NINF', 'savez', 'tensordot', 'cov', 'get_include', 'string_', 'array_equal', 'issubclass_', 'select', 'arcsin',

In [9]:
import numpy as np
#creating a array using numpy
simple_list=[3,4,5]
np.array(simple_list)

array([3, 4, 5])

In [11]:
ar=np.array([1,2,3,4])
print(ar)

[1 2 3 4]


In [13]:
#multidimenssional array
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [19]:
#arange() generates a sequence of numbers within given range
a=np.arange(1,20)
print(a)
b=np.arange(1,100)
print(f"numbers between 1 to 100 is {b}")

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
numbers between 1 to 100 is [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [18]:
c=np.arange(1,20,5) #here 5 is the step between 1 to 20
print(c)

[ 1  6 11 16]


In [20]:
np.arange(20) #by default it will start from 0 if it not mentioned

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
np.ones(5) #it return ones in the given range

array([1., 1., 1., 1., 1.])

In [25]:
np.zeros(5) #it return zeroes in the given range

array([0., 0., 0., 0., 0.])

In [26]:
np.ones((2,3)) #2 rows and 3 columns

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.linspace(2,10,num=5) #it retuns evenly spaced numbers over a interval

array([ 2.,  4.,  6.,  8., 10.])

In [35]:
np.eye(3) #create a identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [41]:
np.random.randint(2,20) #returns a random number in the given interval

19

In [44]:
arr=np.random.randn(2,2) #print a matrix of random numbers 
print(arr)

[[ 0.66532445  0.7820586 ]
 [-1.01599937 -0.26868358]]


In [46]:
arr=np.random.randn(2,3)
arr

array([[-0.4077412 ,  2.34694369,  2.44609701],
       [ 0.85391839, -0.94635078, -0.59510735]])

In [47]:
arr.reshape(3,2) #reshape the array

array([[-0.4077412 ,  2.34694369],
       [ 2.44609701,  0.85391839],
       [-0.94635078, -0.59510735]])

In [48]:
arr.max() #prints max value in the array

2.4460970126234782

In [49]:
arr.min() #prints min value in the array

-0.9463507762804355

In [50]:
arr.T #transpose--> interchanging rows into columns and viceversa

array([[-0.4077412 ,  0.85391839],
       [ 2.34694369, -0.94635078],
       [ 2.44609701, -0.59510735]])

In [53]:
arr.argmax() #returns max indcies in the matrix

2

In [55]:
arr.argmin() #return min index in the matrix

4

In [58]:
sample_array=np.arange(1,20)
sample_array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [60]:
sample_array+sample_array


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [59]:
np.exp(sample_array) # exponential


array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [61]:
#pandas is a library used for working with data sets
#it has a function for analyzing, cleaning,exploring and manipulating data
import pandas 
print(pandas.__dir__()) #printing all libraries of pandas

['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__path__', '__file__', '__cached__', '__builtins__', '__docformat__', '_typing', '_config', '_libs', 'core', 'errors', 'util', 'compat', '_is_numpy_dev', 'get_option', 'set_option', 'reset_option', 'describe_option', 'option_context', 'options', 'pandas', 'io', 'tseries', 'arrays', 'plotting', 'Int8Dtype', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'UInt8Dtype', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'Float32Dtype', 'Float64Dtype', 'CategoricalDtype', 'PeriodDtype', 'IntervalDtype', 'DatetimeTZDtype', 'StringDtype', 'BooleanDtype', 'NA', 'isna', 'isnull', 'notna', 'notnull', 'Index', 'CategoricalIndex', 'RangeIndex', 'MultiIndex', 'IntervalIndex', 'TimedeltaIndex', 'DatetimeIndex', 'PeriodIndex', 'IndexSlice', 'NaT', 'Period', 'period_range', 'Timedelta', 'timedelta_range', 'Timestamp', 'date_range', 'bdate_range', 'Interval', 'interval_range', 'DateOffset', 'to_numeric', 'to_datetime', 'to_timedelta', 'Flags', 'Gro

In [71]:
import pandas as pd
#creating a dataset using pandas 
rows=[["a",1],["b",2],["c",4],["d",5]]
columns=[1,2,3,4]
df=pd.DataFrame(rows,columns)
print(df)

   0  1
1  a  1
2  b  2
3  c  4
4  d  5


In [72]:
df.head() #reading first n values of the table

0  1
1  a  1
2  b  2
3  c  4
4  d  5

In [73]:
df.tail() #reading from last n values of the table

0  1
1  a  1
2  b  2
3  c  4
4  d  5

In [80]:
df.sample() #returns random

0  1
4  d  5

In [75]:
df.info() #prints information about the data

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 1 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       4 non-null      object
 1   1       4 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 96.0+ bytes


In [76]:
df.describe() #returns max,min,mean,std,quartile...

1
count  4.000000
mean   3.000000
std    1.825742
min    1.000000
25%    1.750000
50%    3.000000
75%    4.250000
max    5.000000

In [78]:
df.describe(include="all")

0         1
count     4  4.000000
unique    4       NaN
top       a       NaN
freq      1       NaN
mean    NaN  3.000000
std     NaN  1.825742
min     NaN  1.000000
25%     NaN  1.750000
50%     NaN  3.000000
75%     NaN  4.250000
max     NaN  5.000000

In [83]:
df.isnull().sum() #handling missing values

0    0
1    0
dtype: int64

In [85]:
df.columns #desc columns

RangeIndex(start=0, stop=2, step=1)

In [87]:
df.dtypes #defining data types

0    object
1     int64
dtype: object